BirdsEyeViewPath = "./data/BirdsEye.png"            # Empty background for birdseye view
CamViewPath =  "./data/Cam.png"                     # Empty background for camera view
Cam1TSPath = "./data/Cam1Timestamps_aligned.csv"    # Timestamps for camera 1
PoseModelPath = "./data/PoseConfigs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-420e_body8-256x192.py"               # Pose estimation model
PoseLifterPath = "./data/PoseConfigs/body_3d_keypoint/motionbert/h36m/motionbert_dstformer-ft-243frm_8xb32-120e_h36m.py" # Pose estimation model
yoloWeights = "./data/YoloConfigs/yolov9e.pt"                          # YOLO v8 large size
ClassesListPath = "./data/classes.txt"         # List of COCO classes for YOLO detections
PersonIndex = 0                                     # Index of person on COCO classes list
device = "cuda"                                     # Apple Metal Performance Shader for GPU computation
conf = .5                                           # YOLO model detection confidence 
